import sys
import click

from star_handler.modules.processors.warp2relion import Warp2RelionProcessor
from star_handler.utils.logger import setup_logger
from star_handler.utils.doc_parser import parse_docstring

logger = setup_logger(__name__)

HELP, EPILOG = parse_docstring(Warp2RelionProcessor.__doc__)

@click.command(
    name='process-warp2relion',
    help=HELP,
    epilog=EPILOG
)
@click.option(
    '-f', '--star-file',
    required=True,
    type=click.Path(exists=True, file_okay=True, dir_okay=False),
    help='Path to the input STAR file generated by Warp/MotionCor2.'
)
def main(star_file: str):
    try:
        processor = Warp2RelionProcessor(star_file)
        output_path = processor.process()
        logger.info(f"Successfully converted to: {output_path}")
        
    except Exception as e:
        logger.error(str(e))
        sys.exit(1)

if __name__ == '__main__':
    main()
